header:
    license:
        spdx-id: Apache-2.0
        copyright-owner: Project CHIP Authors

    paths: # `paths` are the path list that will be checked (and fixed) by license-eye, default is ['**'].
        - "**"

    paths-ignore: # `paths-ignore` are the path list that will be ignored by license-eye.
        - "config"
        - "**/connectedhomeip/**"
        - "**/third_party/**"
        - "third_party"
        - ".dependabot"
        - ".github"
        - "dist"
        - "templates"

        - "LICENSE"
        - "NOTICE"
        - ".editorconfig"
        - ".eslintignore"
        - ".gitattributes"
        - ".gitignore"
        - ".node-inspectorrc"
        - ".prettierignore"
        - ".vimrc"
        - ".whitesource"

        - "**/*.md"
        - "**/*.lock"
        - "**/*.yaml"
        - "**/*.yml"
        - "**/*.json"
        - "**/*.toml"
        - "**/*.svg"
        - "**/*.js"

    comment: on-failure # on what condition license-eye will comment on the pull request, `on-failure`, `always`, `never`.
