name: Licenses

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    check:
        name: License Checks
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Check License Header
              uses: apache/skywalking-eyes@main # always prefer to use a revision instead of `main`.
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # needed only when you want License-Eye to comment on the pull request.
