name: Create issues from todos

on:
  workflow_dispatch:
  pull_request:
  push:
#     branches:
#      - master

jobs:
  todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: todo-actions
        uses: dtinth/todo-actions@master
        env:
          GITHUB_TOKEN: ${{ secrets.MATTER_PAT }}
          TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
